# Generated by Django 4.2.7 on 2024-02-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_remove_useraccount_initial_deposit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='balance',
        ),
    ]
