# Generated by Django 4.2.7 on 2024-02-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_remove_useraccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
