# Generated by Django 4.2.7 on 2024-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
