# Generated by Django 4.2.7 on 2024-02-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_buybook_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybook',
            name='returned',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
