# Generated by Django 4.2.7 on 2024-02-14 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_alter_buybook_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buybook',
            old_name='admin_post',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='buybook',
            name='place_order',
        ),
        migrations.AddField(
            model_name='buybook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
