# Generated by Django 4.2.7 on 2024-02-14 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_admin_post_buybook_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buybook',
            old_name='book',
            new_name='admin_post',
        ),
        migrations.RenameField(
            model_name='buybook',
            old_name='user',
            new_name='place_order',
        ),
    ]
