# Generated by Django 4.2.7 on 2024-02-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_review_borrowedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='quantity',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
