# Generated by Django 4.2.7 on 2024-02-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_borrowedbook_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='returend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
