# Generated by Django 4.2.7 on 2024-02-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpost',
            name='book_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
