# Generated by Django 4.2.7 on 2024-02-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_posts', '0002_alter_adminpost_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpost',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
