# Generated by Django 4.2.7 on 2024-02-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_posts', '0004_alter_adminpost_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpost',
            old_name='borrow_price',
            new_name='borrowed_price',
        ),
    ]
