# Generated by Django 4.2.7 on 2024-02-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('admin_posts', '0006_rename_borrowed_price_adminpost_borrow_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpost',
            name='book_category',
            field=models.ManyToManyField(to='categories.categorymodel'),
        ),
    ]
