# Generated by Django 4.2.7 on 2024-02-12 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0006_useraccount_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tranactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after_tranactions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tranaction_type', models.IntegerField(blank=True, choices=[(1, 'Deposit'), (2, 'Borrow Book'), (3, 'Return Book')], null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='auth_user.useraccount')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
