# Generated by Django 4.2.7 on 2024-02-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranactions',
            name='balance_after_tranactions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
