# Generated by Django 4.2.7 on 2024-02-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_posts', '0003_adminpost_timestamp'),
        ('tranactions', '0002_alter_tranactions_balance_after_tranactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_posts.adminpost')),
            ],
        ),
    ]
