# Generated by Django 4.2.7 on 2024-02-12 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_posts', '0003_adminpost_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tranactions', '0003_returnbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbook',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='returnbook',
            name='return_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tranactions',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_posts.adminpost'),
        ),
        migrations.AddField(
            model_name='tranactions',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
