# Generated by Django 4.2.7 on 2024-02-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tranactions', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnBook',
        ),
    ]
