# Generated by Django 4.2.7 on 2024-02-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tranactions', '0006_delete_returnbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
